"""initial schema: users, urls, click_events

Revision ID: 4909c0ae0e73
Revises: 
Create Date: 2026-09-28 10:00:16.107646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4909c0ae0e73'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('urls',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('short_code', sa.String(length=20), nullable=False),
    sa.Column('custom_alias', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_clicks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('custom_alias')
    )
    op.create_index(op.f('ix_urls_created_at'), 'urls', ['created_at'], unique=False)
    op.create_index(op.f('ix_urls_short_code'), 'urls', ['short_code'], unique=True)
    op.create_index('ix_urls_user_id_created_at', 'urls', ['user_id', 'created_at'], unique=False)
    op.create_table('click_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url_id', sa.UUID(), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('referrer', sa.String(length=2048), nullable=True),
    sa.Column('referrer_domain', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['url_id'], ['urls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_click_events_clicked_at'), 'click_events', ['clicked_at'], unique=False)
    op.create_index(op.f('ix_click_events_referrer_domain'), 'click_events', ['referrer_domain'], unique=False)
    op.create_index('ix_click_events_url_id_clicked_at', 'click_events', ['url_id', 'clicked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_click_events_url_id_clicked_at', table_name='click_events')
    op.drop_index(op.f('ix_click_events_referrer_domain'), table_name='click_events')
    op.drop_index(op.f('ix_click_events_clicked_at'), table_name='click_events')
    op.drop_table('click_events')
    op.drop_index('ix_urls_user_id_created_at', table_name='urls')
    op.drop_index(op.f('ix_urls_short_code'), table_name='urls')
    op.drop_index(op.f('ix_urls_created_at'), table_name='urls')
    op.drop_table('urls')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
